version: '3'

networks:
  mynet:
    external: true

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynet
    volumes:
      - ./Glaukos/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
